"""Automata theory module for protocol modeling and pattern recognition.

This module provides various automata formalisms:
- DFA: Deterministic Finite Automata
- NFA: Nondeterministic Finite Automata
- Weighted: Weighted automata with semirings
- Buchi: Buchi automata for omega-regular languages
- Timed: Timed automata with clocks
- Learning: Automata learning (L* algorithm)
- LTL: Linear Temporal Logic specification
"""

from gnsp.automata.dfa import (
    DFA,
    DFAState,
    product_dfa,
    intersection,
    union,
    symmetric_difference,
    minimize,
    are_equivalent,
    from_regex_simple,
    create_tcp_state_machine,
)

from gnsp.automata.nfa import (
    NFA,
    EPSILON,
    subset_construction,
    nfa_union,
    nfa_concatenation,
    nfa_kleene_star,
    nfa_from_symbol,
    nfa_from_epsilon,
    thompson_construction,
    reverse_nfa,
    nfa_to_regex,
)

from gnsp.automata.weighted import (
    Semiring,
    BooleanSemiring,
    ProbabilitySemiring,
    LogProbabilitySemiring,
    TropicalSemiring,
    MaxTropicalSemiring,
    ViterbiSemiring,
    CountingSemiring,
    WeightedAutomaton,
    create_probabilistic_automaton,
    create_tropical_automaton,
    create_counting_automaton,
    AnomalyScoringAutomaton,
)

from gnsp.automata.buchi import (
    BuchiAutomaton,
    product_buchi,
    complement_buchi,
    OnlineMonitor,
    create_safety_monitor,
    create_liveness_monitor,
)

from gnsp.automata.timed import (
    ClockConstraintOp,
    ClockConstraint,
    Guard,
    TimedTransition,
    TimedAutomaton,
    TimedConfiguration,
    TimedSimulator,
    Zone,
    ZoneGraph,
    create_timeout_automaton,
    create_tcp_timeout_automaton,
    create_rate_limiter_automaton,
)

from gnsp.automata.learning import (
    MembershipOracle,
    EquivalenceOracle,
    DFAMembershipOracle,
    DFAEquivalenceOracle,
    ObservationTable,
    LStarLearner,
    RivestSchapireLearner,
    PassiveLearner,
    learn_from_traces,
    learn_protocol_automaton,
)

from gnsp.automata.ltl import (
    LTLOperator,
    LTLFormula,
    prop,
    true_,
    false_,
    not_,
    and_,
    or_,
    implies,
    next_,
    finally_,
    globally,
    until,
    release,
    weak_until,
    to_nnf,
    closure,
    ltl_to_buchi,
    LTLParser,
    parse_ltl,
    LTLMonitor,
    response_pattern,
    absence_pattern,
    universality_pattern,
    precedence_pattern,
    existence_pattern,
    bounded_response,
    mutual_exclusion,
    fairness,
)

__all__ = [
    # DFA
    "DFA",
    "DFAState",
    "product_dfa",
    "intersection",
    "union",
    "symmetric_difference",
    "minimize",
    "are_equivalent",
    "from_regex_simple",
    "create_tcp_state_machine",
    # NFA
    "NFA",
    "EPSILON",
    "subset_construction",
    "nfa_union",
    "nfa_concatenation",
    "nfa_kleene_star",
    "nfa_from_symbol",
    "nfa_from_epsilon",
    "thompson_construction",
    "reverse_nfa",
    "nfa_to_regex",
    # Weighted
    "Semiring",
    "BooleanSemiring",
    "ProbabilitySemiring",
    "LogProbabilitySemiring",
    "TropicalSemiring",
    "MaxTropicalSemiring",
    "ViterbiSemiring",
    "CountingSemiring",
    "WeightedAutomaton",
    "create_probabilistic_automaton",
    "create_tropical_automaton",
    "create_counting_automaton",
    "AnomalyScoringAutomaton",
    # Buchi
    "BuchiAutomaton",
    "product_buchi",
    "complement_buchi",
    "OnlineMonitor",
    "create_safety_monitor",
    "create_liveness_monitor",
    # Timed
    "ClockConstraintOp",
    "ClockConstraint",
    "Guard",
    "TimedTransition",
    "TimedAutomaton",
    "TimedConfiguration",
    "TimedSimulator",
    "Zone",
    "ZoneGraph",
    "create_timeout_automaton",
    "create_tcp_timeout_automaton",
    "create_rate_limiter_automaton",
    # Learning
    "MembershipOracle",
    "EquivalenceOracle",
    "DFAMembershipOracle",
    "DFAEquivalenceOracle",
    "ObservationTable",
    "LStarLearner",
    "RivestSchapireLearner",
    "PassiveLearner",
    "learn_from_traces",
    "learn_protocol_automaton",
    # LTL
    "LTLOperator",
    "LTLFormula",
    "prop",
    "true_",
    "false_",
    "not_",
    "and_",
    "or_",
    "implies",
    "next_",
    "finally_",
    "globally",
    "until",
    "release",
    "weak_until",
    "to_nnf",
    "closure",
    "ltl_to_buchi",
    "LTLParser",
    "parse_ltl",
    "LTLMonitor",
    "response_pattern",
    "absence_pattern",
    "universality_pattern",
    "precedence_pattern",
    "existence_pattern",
    "bounded_response",
    "mutual_exclusion",
    "fairness",
]
